import type { Config } from "tailwindcss";

export const twConfig: Config = {
  content: ["../../apps/**/*{.js,.ts,.jsx,.tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      keyframes: {
        progress: {
          "0%": { width: "0" },
          "100%": { width: "100%" },
        },
      },
      animation: {
        progress: "progress 3500ms linear",
      },
    },
  },
  plugins: [],
  safelist: [
    "w-[8rem]",
    "max-h-[8rem]",
    "aspect-square",
    "bg-slate-50",
    "border-1",
    "text-black",
    "flex",
    "items-center",
    "justify-center",
    "p-2",
    "text-center",
    "cursor-pointer",
    "hover:opacity-[0.95]",
    "justify-between",
    "w-full",
    "px-8",
    "py-4",
    "text-white",
    "text-2xl",
    "py-2",
    "px-3",
    "text-white",
    "bg-purple-900",
    "rounded-md",
    "h-auto",
    "font-semibold",
    "inline-block",
    "h-10",
    "w-10",
    "rounded-full",
    "ring-2",
    "ring-purple-900",
    "max-w-full",
    "p-8",
    "bg-gray-800",
    "rounded-lg",
    "shadow-lg",
    "w-96",
    "text-gray-200",
    "mb-6",
    "px-2",
    "pt-2",
    "pb-4",
    "text-sm",
    "font-medium",
    "rounded",
    "w-5",
    "h-5",
    "text-gray-400",
    "fill-current",
    "flex-grow",
    "h-8",
    "ml-4",
    "bg-transparent",
    "focus:outline-none",
    "font-medium",
    "text-center",
    "text-sm",
    "text-gray-300",
    "h-10",
    "px-2",
    "hover:bg-gray-900",
    "cursor-pointer",
    "cursor-progress",
    "text-transparent",
    "border-2",
    "border-gray-500",
    "px-4",
    "text-ellipsis",
    "overflow-hidden",
    "whitespace-nowrap",
    "grid",
    "grid-rows-1",
    "grid-rows-2",
    "grid-rows-3",
    "grid-rows-4",
    "grid-rows-5",
    "grid-rows-6",
    "grid-rows-7",
    "grid-rows-8",
    "grid-rows-9",
    "grid-rows-10",
    "grid-flow-col",
    "absolute",
    "top-0",
    "right-0",
    "px-1",
    "rounded-sm",
    "font-bold",
    "leading-3",
    "disabled:opacity-70",
    "disabled:cursor-not-allowed",
  ],
};
